### ISSUE TITLE
Template isn't loaded?

### ISSUE THREAD

**Issue by fourroses666** [Nicola1971/ampx#8]
Installed with packagemanager, added the link in the header, but there is no different AMP resource, all chunks and the snippet is installed.

Any idea why the template isn't loaded?
werkplekregisseur.nl/amp?id=4

**Comment by Nicola1971** [comment]
werkplekregisseur.nl/amp?ampid=4

**Comment by fourroses666** [comment]
Accidentally removed it after renaming :( Thx
